fetch:  
    output_path: data/raw/forex_data.csv

preprocess:
    input_path: data/raw/forex_data.csv
    train_path: data/processed/train/forex_data_processed_train.csv
    test_path: data/processed/test/forex_data_processed_test.csv
    test_months: 4
    
train:
  train_path: data/processed/train/forex_data_processed_train.csv
  model_path: models/lstm_model.h5
  scaler_path: models/scaler.pkl

  sequence_length: 50

  validation_months: 4

  lstm_params:
    units_1: [32, 64]
    units_2: [16, 32]
    dropout: [0.1, 0.2]
    batch_size: [32, 64]
    epochs: 10


    

train_lstm:
  train_path: data/processed/train/forex_data_processed_train.csv
  model_path: models/lstm_model.h5
  stats_path: models/lstm_feature_stats.pkl
  lookback: 50
  window: 20
  validation_months: 4
  patience: 10
  seed: 100
  registered_model_name: LSTMFXTradingModel
  param_grid:
    units_1: [32, 64]
    units_2: [16, 32]
    dropout: [0.1, 0.2]
    batch_size: [32, 64]
    epochs: [10]
    learning_rate: [0.001, 0.0005]

evaluate:
  test_path: data/processed/test/forex_data_processed_test.csv
  model_path: models/lstm_model.h5
  stats_path: models/lstm_feature_stats.pkl

live-stream:
    